site_name: SNT & NSI
copyright: Réalisé par M. NICOLAS
extra_css:
  - extra.css
extra:
  generator: false
  analytics:
    provider: google
    property: G-82YG19J1ZT
theme:
  name: material
  language: fr
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - navigation.sections
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      primary: teal
      accent: green
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      primary: teal
      accent: green
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys:
      key_map: { 'enter': 'Entrée' }
  - def_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search:
      lang: fr
  - glightbox
nav:
  - Home: index.md
  - SNT:
      - Web:
          - Introduction: snt/web1.md
          - Activité URL: snt/web2.md
      - Internet:
          - Introduction: snt/internet-1.md
          - Enquête Internet: snt/enquete-internet.md
          - Protocole TCP/IP: snt/internet-2.md
          - Routage des paquets: snt/internet-3.md
      - Les Réseaux Sociaux:
          - Repères, chiffres et dates: snt/rsociaux.md
          - Recherche documentaire: snt/rsociaux-acti.md
          - Les graphes: snt/rs-graphes.md
          - Activité graphes: snt/acti-graphes.md
          - Analyse d'un RS: snt/rs-analyse.md
          - Excaligraphes: snt/excaligraphes.md
          - Le Petit Monde: snt/petit-monde.md
  - NSI:
      - Représentation des types:
          - Entiers positifs: nsi/types-base/entiers.md
          - Entiers - activité: nsi/types-base/entiers-acti.md
          - Entiers signés: nsi/types-base/entiers-sign.md
      - Bases du Python:
          - Variables et types natifs: nsi/python-bases/python1.md
          - Thonny: nsi/python-bases/python-acti1.md
          - Conditions et tests: nsi/python-bases/python-tests.md
          - Mini-quizz: nsi/python-bases/python-acti2.md
          - Mini-quizz (c): nsi/python-bases/python-acti2-c.md
          - Boucles while / for: nsi/python-bases/python-while.md
          - Compte à rebours: nsi/python-bases/python-while-acti.md
          - Fonctions: nsi/python-bases/python-fonctions.md
          #- Types construits: nsi/python-bases/python-types.md
          #- Activités supp.: nsi/python-bases/python-acti2-p.md
          - Activités fonctions: nsi/python-bases/python-func-acti.md
          - Activités fonctions (c): nsi/python-bases/python-func-acti-c.md
          - Séquences et boucles for: nsi/python-bases/python-seq.md
          - Activités séquences: nsi/python-bases/python-seq-acti.md
          - Bilan: nsi/python-bases/python-bases-bilan.md
          - Projet: nsi/python-bases/python-projet.md
  #- changelog: changelog.md
